package com.example.demo.Entities;

public enum Permissions {
    // Patient
    PATIENT_VIEW_OWN_DATA,
    PATIENT_UPDATE_OWN_DATA,
    PATIENT_VIEW_APPOINTMENTS,
    PATIENT_VIEW_OWN_RECORDS,
    PATIENT_VIEW_VITALS,

    // Doctor
    DOCTOR_VIEW_ASSIGNED_PATIENTS,
    DOCTOR_ADD_MEDICAL_RECORDS,
    DOCTOR_MANAGE_APPOINTMENTS,

    // Nurse
    NURSE_RECORD_PATIENTS,
    NURSE_VIEW_VITALS,

    // Admin
    ADMIN_MANAGE_USERS,
    ADMIN_CREATE_DOCTORS_NURSES,
    ADMIN_MANAGE_APPOINTMENTS

}
